pages:
  stage: deploy
  script:
    - mkdir -p public

    - cp -r *.html *.css *.js public/
    - cp -r images/ public/
    - cp -r favicons/ public/

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "main"